version: 2

updates:
  # Handle PyPI updates
  - package-ecosystem: pip
    directory: "/ci"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Denver"
    allow:
      - dependency-type: all
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Type: Maintenance"
      - "Area: Infrastructure"
    commit-message:
      prefix: "CI: "
      include: "scope"
    groups:
      flake8:
        patterns:
          - "flake8*"
          - "pycodestyle"
          - "pyflakes"

  # Update GitHub Actions versions in workflows
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/.github/actions/build-docs"
      - "/.github/actions/install-conda"
      - "/.github/actions/install-pypi"
      - "/.github/actions/run-tests"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: all
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Type: Maintenance"
      - "Area: Infrastructure"
    commit-message:
      prefix: "CI: "
      include: "scope"
